# Generated by Django 6.0.4 on 2026-05-08 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
