# Generated by Django 6.0.4 on 2026-05-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='discountPercentage',
            new_name='discount_percentage',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
