# Generated by Django 6.0.4 on 2026-05-10 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_createdat_product_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='review',
        ),
    ]
